import {Stack} from '../stack';
import {StackGroup} from '../enums/stack-group.enum';
import {CardValue} from '../enums/card-value.enum';
import {Suit} from '../enums/suit.enum';

export const tamariz = new Stack(
  'tamariz',
  'Tamariz',
  StackGroup.Memorized,
  [
    {value: CardValue.four, suit: Suit.clubs},
    {value: CardValue.two, suit: Suit.hearts},
    {value: CardValue.seven, suit: Suit.diamonds},
    {value: CardValue.three, suit: Suit.clubs},
    {value: CardValue.four, suit: Suit.hearts},
    {value: CardValue.six, suit: Suit.diamonds},
    {value: CardValue.ace, suit: Suit.spades},
    {value: CardValue.five, suit: Suit.hearts},
    {value: CardValue.nine, suit: Suit.spades},
    {value: CardValue.two, suit: Suit.spades},
    {value: CardValue.queen, suit: Suit.hearts},
    {value: CardValue.three, suit: Suit.diamonds},
    {value: CardValue.queen, suit: Suit.clubs},
    {value: CardValue.eight, suit: Suit.hearts},
    {value: CardValue.six, suit: Suit.spades},
    {value: CardValue.five, suit: Suit.spades},
    {value: CardValue.nine, suit: Suit.hearts},
    {value: CardValue.king, suit: Suit.clubs},
    {value: CardValue.two, suit: Suit.diamonds},
    {value: CardValue.jack, suit: Suit.hearts},
    {value: CardValue.three, suit: Suit.spades},
    {value: CardValue.eight, suit: Suit.spades},
    {value: CardValue.six, suit: Suit.hearts},
    {value: CardValue.ten, suit: Suit.clubs},
    {value: CardValue.five, suit: Suit.diamonds},
    {value: CardValue.king, suit: Suit.diamonds},
    {value: CardValue.two, suit: Suit.clubs},
    {value: CardValue.three, suit: Suit.hearts},
    {value: CardValue.eight, suit: Suit.diamonds},
    {value: CardValue.five, suit: Suit.clubs},
    {value: CardValue.king, suit: Suit.spades},
    {value: CardValue.jack, suit: Suit.diamonds},
    {value: CardValue.eight, suit: Suit.clubs},
    {value: CardValue.ten, suit: Suit.spades},
    {value: CardValue.king, suit: Suit.hearts},
    {value: CardValue.jack, suit: Suit.clubs},
    {value: CardValue.seven, suit: Suit.spades},
    {value: CardValue.ten, suit: Suit.hearts},
    {value: CardValue.ace, suit: Suit.diamonds},
    {value: CardValue.four, suit: Suit.spades},
    {value: CardValue.seven, suit: Suit.hearts},
    {value: CardValue.four, suit: Suit.diamonds},
    {value: CardValue.ace, suit: Suit.clubs},
    {value: CardValue.nine, suit: Suit.clubs},
    {value: CardValue.jack, suit: Suit.spades},
    {value: CardValue.queen, suit: Suit.diamonds},
    {value: CardValue.seven, suit: Suit.clubs},
    {value: CardValue.queen, suit: Suit.spades},
    {value: CardValue.ten, suit: Suit.diamonds},
    {value: CardValue.six, suit: Suit.clubs},
    {value: CardValue.ace, suit: Suit.hearts},
    {value: CardValue.nine, suit: Suit.diamonds}
  ]
);
